num_envs: 60
num_eval_envs: 32
lr: 0.0003
max_it: 1000
max_grad_norm: 0.4
seed: 0
demo_replay_mode: random
threshold: 0.4
normalize_observations: True
cycle_len: 108
ep_len: 60
ep_len_eval: 108
use_lr_scheduler: True
reward_scaling: 0.02
rot_weight: 0.5
vel_weight: 0.01
ang_weight: 0.01
n_frames: 20
# obs_type: joint
# root_pos_xy_weight: 0.1
# root_pos_z_weight: 0.5
# root_ori_weight: 0.1
# joint_weight: 0.5

ref: data/demo_a1/jump_backward_flip_50Hz.npy # (108, 739)
