num_envs: 96
num_eval_envs: 32
lr: 0.0003
max_it: 1000
max_grad_norm: 0.4
seed: 0
demo_replay_mode: threshold
threshold: 0.4
normalize_observations: True
cycle_len: 44
ep_len: 25
ep_len_eval: 44
use_lr_scheduler: True
reward_scaling: 0.02
rot_weight: 0.5
vel_weight: 0.01
ang_weight: 0.01
n_frames: 25

ref: data/demo_a1/jump_backward_flip_20Hz.npy # (44, 739)
