num_envs: 300
num_eval_envs: 32
lr: 0.0003
max_it: 1000
max_grad_norm: 0.4
seed: 0
system_config: swordshield
demo_replay_mode: threshold
threshold: 0.2
normalize_observations: True
ep_len: 96
obs_type: target_state
reward_scaling: 0.02
rot_weight: 0.5
vel_weight: 0.01
ang_weight: 0.01
use_lr_scheduler: True

ref: data/demo_swordshield/RL_Avatar_Atk_2xCombo01_Motion.npy